### ISSUE TITLE
NextJS & Docker

### ISSUE THREAD

**Issue by TephrosisDEV** [spatie/next-ray#1]
Hello, 

None of the ray calls I'm calling are listed in the Ray app
I am using Docker though, does anyone have the same problem?
I want to use it to improve debugging when facing errors on server components ;)

**Comment by patinthehat** [comment]
@TephrosisDEV I'd be interested to chat about your use case, I haven't tested node-ray (which next-ray, react-ray, etc. are built on) for react server components.  Please reach out to me via email, twitter, or linkedIn if you'd like to have a quick chat so I can make the packages better for everyone. Thanks!
