### ISSUE TITLE
Get Error [TypeError]: Cannot read properties of null (reading 'groups') in NextJS 14.2.3 (on Win11)

### ISSUE THREAD

**Issue by jefiedler** [spatie/next-ray#2]
Dear Dev Team, 
I am trying to use Ray in NextJS 14.2.3. However, I get the `Error [TypeError]: Cannot read properties of null (reading 'groups')`.

I have stored the local path in the `.env` file as in the instructions and then imported `ray` in the `./src/app/page.ts` and tested it. Unfortunately, I got the above error.

Any help?

Thanks for your help. 

Error:
![image](https://github.com/spatie/next-ray/assets/68224198/96257353-1d3c-4f30-ac42-82567c83a38d)
![image](https://github.com/spatie/next-ray/assets/68224198/e1c4203d-53df-48d0-b73f-5208f7b814fd)

No use Client: 
![image](https://github.com/spatie/next-ray/assets/68224198/f33a58bd-482b-41c7-949e-bb5cde0b5f25)
![image](https://github.com/spatie/next-ray/assets/68224198/66ec0e41-e77e-4240-b47b-5ff74251fcc7)

My Dev-Setup:

- Windows 11
- NextJS:  14.2.3
- node.js: v21.6.1
- package manager:  bun 1.1.6
- Ray App: 2.7.5.0

**Comment by patinthehat** [comment]
@jefiedler Try using the package that this one uses, [`node-ray`](https://github.com/permafrost-dev/node-ray). Do you still run into the same issue?

**Comment by jefiedler** [comment]
@patinthehat Thanks for your help, and please excuse the delayed response from me.  With `node-ray` (use server files) and `react-ray` (use client files) it works. 

Maybe it makes sense eventually to mark `next-ray` as archived or something. Because it is a bit confusing.

**Comment by patinthehat** [comment]
@jefiedler Thanks for following up, I'm glad you were able to get it working :smile: 

I'll see what we can do about updating this package to get it in line with the other node-ray-based integrations. :+1:

**Comment by patinthehat** [comment]
Thanks again! :+1:

**Comment by justrustyspoons** [comment]
I have the same issue
